version: "3.7"

# Settings in this file override or add to those in docker-compose.yml. 
# Add anything that needs to be changed manually. (This is unusual).
# Docker-compose.yml will not be overwritten on upgrade.
# For example:

services:

  sfacctd_1:
    ports:
      # port on host receiving flow data : port in the container
      - "${sflowPort_1}:${sflowContainerPort_1}/udp"

  nfacctd_1:
    ports:
      # port on host receiving flow data : port in the container
      - "${netflowPort_1}:${netflowContainerPort_1}/udp"
 
