version: "3.7"
services:

  logstash:
    image: tacc/netsage_pipeline:v2.1.0
    ## If you need to override JVM options, uncomment these lines
    #   volumes:
    #     - ./userConfig/jvm.options:/usr/share/logstash/config/jvm.options

  importer:
    image: tacc/netsage_importer:v2.1.1
    logging:
      driver: json-file
      options:
        max-size: "10g"
        max-file: "6"
    ## If you add additional collectors or need to make other changes in the importer "shared" config, 
    ## use the netsage_override.xml file and uncomment the following lines 
    #   volumes:
    #     - ./userConfig/netsage_override.xml:/tmp/conf/netsage_shared.xml

  ## Modify port numbers as needed, and add any additional collectors here (see Docker Advanced documentation).  
  ## Remove any collectors that do not need to be running.
  sflow-collector:
    image: tacc/netsage_collector:v2.1.0
    restart: always
    command: sfcapd -w /data -S 1 -z -p 9999
    volumes:
      - ./data/input_data/sflow:/data
    ports:
      - "9998:9998/udp"
  netflow-collector:
    image: tacc/netsage_collector:v2.1.0
    command: nfcapd -w /data -S 1 -z -p 9999
    ports:
      - "9999:9999/udp"
    restart: always
    volumes:
      - ./data/input_data/netflow:/data
