version: "3.7"
services:

  logstash:
    image: tacc/pipeline_logstash:latest
    ## If you need to override JVM options, uncomment these lines
    #   volumes:
    #     - ./userConfig/jvm.options:/usr/share/logstash/config/jvm.options

  importer:
    image: tacc/pipeline_importer:latest
    ## If you add additional collectors or need to make other changes in the importer "shared" config, 
    ## use the netsage_override.xml file and uncomment the following lines 
    #   volumes:
    #     - ./userConfig/netsage_override.xml:/etc/grnoc/netsage/deidentifier/netsage_shared.xml

  ## Modify port numbers as needed, and add any additional collectors here (see Docker Advanced documentation).  
  ## Remove any collectors that do not need to be running.
  sflow-collector:
    image: netsage/nfdump-collector:alpine-1.6.23
    restart: always
    command: sfcapd -T all -l /data -S 1 -w -z -p 9998
    volumes:
      - ./data/input_data/sflow:/data
    ports:
      - "9998:9998/udp"
  netflow-collector:
    image: netsage/nfdump-collector:alpine-1.6.23
    command: nfcapd -T all -l /data -S 1 -w -z -p 9999
    ports:
      - "9999:9999/udp"
    restart: always
    volumes:
      - ./data/input_data/netflow:/data
