version: "3.7"

# Docker services and settings. 
# The non-example version of this file is created by setup-pmacct-compose.sh.
# Use the override file for any manual overrides.

# Shared network for the containers. Processes will be able to communicate over default ports.
networks:
    netsage-network:

# Reusable blocks of settings
x-default-pmacct-settings:
  &pmacct-defaults
    env_file: 
     - .env
    volumes:
      # location of configs on host : location in container : read-only
      - ./conf-pmacct:/etc/pmacct:ro
    networks:
      - netsage-network
    depends_on:
      - rabbit

x-default-sfacct-settings:
  &sflow-defaults
    image: 
      - ghcr.io/netsage-project/sfacctd:7Jun2022

x-default-nfacct-settings:
  &netflow-defaults
    image: 
      - ghcr.io/netsage-project/nfacctd:7Jun2022

# The containers  (setup script needs to have them in this order)
services:

  sfacctd_1:
    container_name: sfacctd_1
    << : *pmacct-defaults
    << : *sflow-defaults
    command:
      # parameters for the sfacctd command 
      - -f 
      - /etc/pmacct/sfacctd_1.conf
    ports:
      # port on host receiving flow data : port in the container
      - "${sflowPort_1}:${sflowContainerPort_1}/udp"
 
  nfacctd_1:
    container_name: nfacctd_1
    << : *pmacct-defaults
    << : *netflow-defaults
    command:
      # parameters for the nfacctd command 
      - -f 
      - /etc/pmacct/nfacctd_1.conf
    ports:
      # port on host receiving flow data : port in the container
      - "${netflowPort_1}:${netflowContainerPort_1}/udp"
 
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.9-management
    env_file: .env
    ports:
      # The port for the UI needs to be mapped to that on the host
      # To view, go to https://<host>/rabbit
      - "15672:15672"
    volumes:
      # Use a named Volume for the rabbitmq config and files for its own use. 
      # We want data (msgs in the queue) to persist but don't need to see it.
      - rabbit_vol:/var/lib/rabbitmq
    networks: 
      - netsage-network

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.2
    env_file: .env
    # user uid
    user: 1000:1000
    # Explicitly specify *.conf to be sure logstash doesn't use *.disabled configs. 
    command: logstash -f /etc/logstash/conf.d/*.conf
    volumes:
      # location of logstash configs on host : location within container : read-only
      - ./conf-logstash/:/etc/logstash/conf.d/:ro
      # location of downloaded maxmind and caida files on host : location within container : read-only 
      - ./logstash-downloads/:/var/lib/grnoc/netsage/:ro  
      # location for aggregation map files, which save flows being aggregated when logstash shuts down
      - ./logstash-temp/:/logstash-temp/
    networks: 
      - netsage-network
    depends_on:
      - rabbit
    # restart is not included since if logstash dies, there may be an error and we dont' want it to keep restarting over and over
  
# named volumes 
volumes:
    rabbit_vol:

