version: "3.7"
services:
  importer:
    image: tacc/pipeline_importer:latest
    build:
      context: .
      dockerfile: compose/importer/Dockerfile
  logstash:
    image: tacc/pipeline_logstash:latest
    build:
      context: .
      dockerfile: ./compose/logstash/Dockerfile
