#!/usr/bin/perl

#####  I believe this was used for development and to read files created by the old netsage-flow-archive pipeline piece
#####  Reads json files which are rabbitmq messages which are batches of 100 flows.
#####  Used with RawDataImporter.pm

use strict;
use warnings;

use GRNOC::NetSage::Deidentifier::RawDataImporter;

use Getopt::Long;
use Data::Dumper;

### constants ###

use constant DEFAULT_CONFIG_FILE => '/etc/grnoc/netsage/deidentifier/netsage_raw_data_importer.xml';
use constant DEFAULT_LOGGING_FILE => '/etc/grnoc/netsage/deidentifier/logging.conf';

### command line options ###

my $config = DEFAULT_CONFIG_FILE;
my $logging = DEFAULT_LOGGING_FILE;
my $nofork;
my @files;
my $help;

GetOptions( 'config=s' => \$config,
            'logging=s' => \$logging,
            'nofork' => \$nofork,
            'file=s{1,}' => \@files,
            'help|h|?' => \$help );

# did they ask for help?
usage() if $help;

# start/daemonize writer
my $raw_importer = GRNOC::NetSage::Deidentifier::RawDataImporter->new( config_file => $config,
                                                          logging_file => $logging,
                                                          daemonize => !$nofork,
                                                          files => \@files,
                                                          process_name => "netsage_raw_data_importer",
                                                          task_type => "noinput" );

$raw_importer->start("no_input_queue");

### helpers ###

sub usage {

    print "Usage: $0 [--config <file path>] [--logging <file path>] [--jsonfile <file path>]\n";

    exit( 1 );
}
