#!/bin/sh
#
# netsage-netflow-importer-daemon        init file for starting up the NetSage Netflow importer daemon
#
# chkconfig:   2345 20 80
# description: Starts and stops the NetSage Netflow Importer daemon

# Source function library.
. /etc/rc.d/init.d/functions

name="netsage-netflow-importer-daemon"
exec="/usr/bin/$name"
## The pid file name is actually set in the deidentifier config file!
## This is just using that name.
pidfile="/var/run/$name.pid"
CONFIG="/etc/grnoc/netsage/deidentifier/netsage_netflow_importer.xml"
SHAREDCONFIG="/etc/grnoc/netsage/deidentifier/netsage_shared.xml"

start() {
    [ -f $CONFIG ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon "$exec --config $CONFIG --sharedconfig $SHAREDCONFIG"
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    if [ -f $pidfile ]
    then
        # shutdown doesn't work, try old way
        killproc -p $pidfile $name
        retval=$?
    else
        success "$name shutdown"
    fi
    echo -n $"Use ps aux to be sure the daemon and worker both stopped !!"
    echo
    return $retval
}

# workers don't always quit, certainly not quickly!
restart() {
   echo -n $"Use stop, check ps aux, then start"
   echo
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
