#!/bin/sh
#
# netsage-flow-filter-daemon        init file for starting up the NetSage FlowFilter daemon
#
# chkconfig:   2345 20 80
# description: Starts and stops the NetSage FlowFilter daemon

# Source function library.
. /etc/rc.d/init.d/functions

name="netsage-flow-filter-daemon"
exec="/usr/bin/$name"
## I believe the pid file name is actually set in the deidentifier config! 
## This is just using that name.
pidfile="/var/run/$name.pid"
CONFIG="/etc/grnoc/netsage/deidentifier/netsage_flow_filter.xml"
SHAREDCONFIG="/etc/grnoc/netsage/deidentifier/netsage_shared.xml"

start() {
    [ -f $CONFIG ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon "$exec --config $CONFIG" --sharedconfig $SHAREDCONFIG
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    if [ -f $pidfile ]
    then
        # shutdown haven't work, try old way
        killproc -p $pidfile $name
        retval=$?
    else
        success "$name shutdown"
    fi
    echo -n $"Use ps aux to be sure the worker has stopped also"
    echo
    return $retval
}

restart() {
    echo -n $"Use stop, check with ps, then start"
    echo
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
